### ISSUE TITLE
Login failed with error (undefined)

### ISSUE THREAD

**Issue by MahmoudBehery** [passwordcockpit/passwordcockpit#74]
Hi,
after fresh installation, i tried to login to web interface and got an error undefined.
![image](https://user-images.githubusercontent.com/132373275/235699485-53ecc178-d3ff-4d27-9918-43104a5c9f26.png)

**Comment by bu3tt1** [comment]
Please, enable debugging mode with PASSWORDCOCKPIT_DEBUG: true and send the description of the error.

**Comment by bu3tt1** [comment]
Does the problem still persist?

**Comment by uncle-lozio-bob** [comment]
Hi, i have same error, after installation, when i try to login with admin.
Where i found the error description?

**Comment by uncle-lozio-bob** [comment]
Problem solved with this issues [https://github.com/passwordcockpit/passwordcockpit/issues/3](url)

**Comment by martan-network** [comment]
I'm also experiencing this issue. Please see yml config below:

version: "3.5"
services:
    passwordcockpit:
        image: passwordcockpit/passwordcockpit:1.4.0
        container_name: passwordcockpit
        ports:
            - "4343:4343"
        volumes:
            - ./volumes/upload:/var/www/html/upload
        environment:
            PASSWORDCOCKPIT_DATABASE_USERNAME: passwordcockpit_dbusr
            PASSWORDCOCKPIT_DATABASE_PASSWORD: password
            PASSWORDCOCKPIT_DATABASE_HOSTNAME: mysqldb
            PASSWORDCOCKPIT_DATABASE_DATABASE: passwordcockpit
            PASSWORDCOCKPIT_BLOCK_CIPHER_KEY: supersecretkey
            PASSWORDCOCKPIT_AUTHENTICATION_SECRET_KEY: authenticationsecretkey
            PASSWORDCOCKPIT_BASEHOST: https://elpwdcockpit:4343
            PASSWORDCOCKPIT_AUTHENTICATION_TYPE: password
            PASSWORDCOCKPIT_SWAGGER: enable
            PASSWORDCOCKPIT_SSL: enable
            PASSWORDCOCKPIT_UPLOAD_ACCEPTED_MIMETYPES: 'pdf,zip'
        depends_on:
            - mysqldb
    mysqldb:
        image: mysql:8.4.2
        container_name: mysqldb
        ports:
            - 3306:3306
        volumes:
            - ./volumes/mysqldb:/var/lib/mysqldb
        environment:
            MYSQL_DATABASE: passwordcockpit
            MYSQL_USER: passwordcockpit_dbusr
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root_password
        command: --character-set-server=utf8 --collation-server=utf8_unicode_ci

**Comment by bu3tt1** [comment]
The certificate is valid?

**Comment by martan-network** [comment]
![validcert](https://github.com/user-attachments/assets/d46eae7f-0c6b-4465-8549-63fb58d20446)


added a screenshot of the valid cert. does that yml config work for you?

**Comment by bu3tt1** [comment]
**First note**
With this docker-compose.yml the https work fine:

```
version: "3.5"
services:
    passwordcockpit:
        image: passwordcockpit/passwordcockpit:1.4.0
        container_name: passwordcockpit
        ports:
            # Use with PASSWORDCOCKPIT_SSL: disable
            #- "8080:8080"
            # Use with PASSWORDCOCKPIT_SSL: enable
            - "4343:4343"
        volumes:
            - ./volumes/upload:/var/www/html/upload
            # Overwrite self-signed SSL certificate file
            #- ./volumes/ssl_certificate/passwordcockpit.crt:/etc/ssl/certs/passwordcockpit.crt:ro
            #- ./volumes/ssl_certificate/passwordcockpit.key:/etc/ssl/certs/passwordcockpit.key:ro
            # User and group same as host when use APACHE_RUN_USER and APACHE_RUN_GROUP
            #- /etc/group:/etc/group:ro
            #- /etc/passwd:/etc/passwd:ro
            #- /etc/shadow:/etc/shadow:ro
        environment:
            PASSWORDCOCKPIT_DATABASE_USERNAME: passwordcockpit_db_usr
            PASSWORDCOCKPIT_DATABASE_PASSWORD: password
            PASSWORDCOCKPIT_DATABASE_HOSTNAME: mariadb
            PASSWORDCOCKPIT_DATABASE_DATABASE: passwordcockpit
            PASSWORDCOCKPIT_BLOCK_CIPHER_KEY: supersecretkey
            PASSWORDCOCKPIT_AUTHENTICATION_SECRET_KEY: authenticationsecretkey
            # Use with PASSWORDCOCKPIT_SSL: disable
            #PASSWORDCOCKPIT_BASEHOST: http://localhost:8080
            # Use with PASSWORDCOCKPIT_SSL: enable
            PASSWORDCOCKPIT_BASEHOST: https://localhost:4343
            PASSWORDCOCKPIT_AUTHENTICATION_TYPE: password
            PASSWORDCOCKPIT_SWAGGER: enable
            PASSWORDCOCKPIT_SSL: enable
            #PASSWORDCOCKPIT_ADMIN_PASSWORD: Password123!
            #APACHE_RUN_USER: 1000
            #APACHE_RUN_GROUP: 1000
            #PASSWORDCOCKPIT_LDAP_USER_ATTR_UNIQUE_IDENTIFIER: ''
            #PASSWORDCOCKPIT_LDAP_USER_ATTR_NAME: ''
            #PASSWORDCOCKPIT_LDAP_USER_ATTR_SURNAME: ''
            #PASSWORDCOCKPIT_LDAP_USER_ATTR_MAIL: ''
            #PASSWORDCOCKPIT_LDAP_USER_ATTR_PHONE: ''
            #PASSWORDCOCKPIT_LDAP_HOST: ''
            #PASSWORDCOCKPIT_LDAP_PORT: 389
            #PASSWORDCOCKPIT_LDAP_USERNAME: ''
            #PASSWORDCOCKPIT_LDAP_PASSWORD: ''
            #PASSWORDCOCKPIT_LDAP_BASEDN: ''
            #PASSWORDCOCKPIT_LDAP_ACCOUNTFILTERFORMAT: ''
            #PASSWORDCOCKPIT_LDAP_BINDREQUIRESDN: 'true'
            PASSWORDCOCKPIT_UPLOAD_ACCEPTED_MIMETYPES: 'pdf,zip'
            #PASSWORDCOCKPIT_DEBUG: true
        depends_on:
            - mariadb
    mariadb:
        image: mariadb:10
        container_name: mariadb
        ports:
            - '3306:3306'
        volumes:
            - ./volumes/mariadb:/var/lib/mysql
        environment:
            - MARIADB_ROOT_PASSWORD=root_password
            - MARIADB_USER=passwordcockpit_db_usr
            - MARIADB_PASSWORD=password
            - MARIADB_DATABASE=passwordcockpit
        command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
```

Important is to access via the URL `https://localhost:4343/`, if you use `127.0.0.1` you receive a `strict-origin-when-cross-origin`.

Can you please try with this docker-compose.yml?

**Second note**
In your docker-compose.yml you use the following URL `https://elpwdcockpit:4343/`.

The domain `elpwdcockpit` point to the right IP?
Have you tried pinging the domain?

I see also that the self-signed SSL certificate is not overwritten:
```
volumes:
            - ./volumes/upload:/var/www/html/upload
            # Overwrite self-signed SSL certificate file
            - ./volumes/ssl_certificate/passwordcockpit.crt:/etc/ssl/certs/passwordcockpit.crt:ro
            - ./volumes/ssl_certificate/passwordcockpit.key:/etc/ssl/certs/passwordcockpit.key:ro
```
Maybe you have to configure it.

**Third note**
Please send the result of the inspect network tab, to understand, it is important to see the response of the network.
