### ISSUE TITLE
LDAP Connection

### ISSUE THREAD

**Issue by yuriprawucki1** [passwordcockpit/passwordcockpit#85]
Hi, I'm building my environment like this:

```
version: '3.5'

services:
  cockpit:
    image: passwordcockpit/passwordcockpit:1.3.5
    volumes:
      - /passwordcockpit/upload:/var/www/html/upload
    user: '$UID:$GID'
    environment:
      TZ: America/Sao_Paulo
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
      PASSWORDCOCKPIT_DATABASE_USERNAME: passwordcockpituser
      PASSWORDCOCKPIT_DATABASE_PASSWORD: pass123
      PASSWORDCOCKPIT_DATABASE_HOSTNAME: database
      PASSWORDCOCKPIT_DATABASE_DATABASE: passwordcockpit
      PASSWORDCOCKPIT_BLOCK_CIPHER_KEY: pass123
      PASSWORDCOCKPIT_AUTHENTICATION_SECRET_KEY: pass123
      PASSWORDCOCKPIT_BASEHOST: https://192.168.1.2
      PASSWORDCOCKPIT_SWAGGER: enable
      PASSWORDCOCKPIT_SSL: enable
      PASSWORDCOCKPIT_AUTHENTICATION_TYPE: ldap
      PASSWORDCOCKPIT_ADMIN_PASSWORD: pass123
      PASSWORDCOCKPIT_UPLOAD_ACCEPTED_MIMETYPES: 'pdf'
      PASSWORDCOCKPIT_LDAP_HOST: 192.168.1.200
      PASSWORDCOCKPIT_LDAP_PORT: 389
      PASSWORDCOCKPIT_LDAP_USERNAME: CN=svcLdap,CN=Users,DC=domain,DC=local
      PASSWORDCOCKPIT_LDAP_PASSWORD: pass123
      PASSWORDCOCKPIT_LDAP_BASEDN: DC=domain,DC=local
      PASSWORDCOCKPIT_LDAP_ACCOUNTFILTERFORMAT: (&(memberOf=CN=PassUsers,OU=MyGroups,DC=domain,DC=local)(samaccountname=%s))
      PASSWORDCOCKPIT_LDAP_BINDREQUIRESDN: 'false'
      PASSWORDCOCKPIT_LDAP_USER_ATTR_UNIQUE_IDENTIFIER: 'samaccountname'
      PASSWORDCOCKPIT_LDAP_USER_ATTR_NAME: 'givenname'
      PASSWORDCOCKPIT_LDAP_USER_ATTR_SURNAME: 'sn'
      PASSWORDCOCKPIT_LDAP_USER_ATTR_MAIL: 'mail'
      PASSWORDCOCKPIT_LDAP_USER_ATTR_PHONE: 'telephonenumber'
      PASSWORDCOCKPIT_DEBUG: 'true'
    ports:
      - "443:4343"
    depends_on:
      - database
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  database:
    image: mariadb:10.11.2
    #volumes:
      #/passwordcockpit/database:/var/lib/mysql
      #/passwordcockpit/backups:/backups
    user: '$UID:$GID'
    environment:
      MARIADB_ROOT_PASSWORD: pass123
      MARIADB_DATABASE: passwordcockpit
      MARIADB_USER: passwordcockpituser
      MARIADB_PASSWORD: pass123
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
```

However, I cannot log in to the system, neither with the user I entered to integrate with LDAP nor with another AD user.

![image](https://github.com/passwordcockpit/passwordcockpit/assets/29665844/84c00596-0c09-4225-b99a-a13d11c38b79)
